### ISSUE TITLE
NASHPY strengh 

### ISSUE THREAD

**Issue by devdell** [drvinceknight/Nashpy#172]
hello everyone , im data scientist student and im going to make a thesis  where i will use game strategy so as i see nashpy is the library in python, i want to know some few things : if :
1- the library can support a big size of data .
2- also if gives a good precision results when we put a big matrix with big rows and column .

**Comment by drvinceknight** [comment]
Hi @devdell, apologies for the delayed response.

For both of your questions the short answer is "it depends".


> 1- the library can support a big size of data .

By big data I assume you mean the size of the payoff matrices. The limitations are more computational complexity than nashpy itself.

If you want to find all nash equilibria, then support enumeration should return results in realistic time for up to a 10 by 10 size game

If you want to find *a* nash equilibria than the Lemke Howson algorithm should return results reliably for larger games.

If you want to look at learned behaviour and potential emergent equilibria then the learning algorithms can handle games of any size (subject to the memory of your machine of course).

> 2- also if gives a good precision results when we put a big matrix with big rows and column .

This would depend on whether or not the matrices are degenerate or not.
