### ISSUE TITLE
Too low numpy version requirement in pyproject.toml

### ISSUE THREAD

**Issue by eliphatfs** [drvinceknight/Nashpy#178]
For example, in algorithms/lemke_howson:

https://github.com/drvinceknight/Nashpy/blob/5876635d27ca32aae0bea2cf9cb5ce57267f9af7/src/nashpy/algorithms/lemke_howson.py#L15

`numpy.typing.NDArray` is referenced. This API is new in numpy version 1.21 (https://numpy.org/devdocs/reference/typing.html#numpy.typing.NDArray). However, the toml only requires `numpy>=1.15`.

**Comment by drvinceknight** [comment]
Thank you for identifying this, I'd noticed the problem but hadn't figured out where it was specifically. I'll open a new PR and do a new release right now. 🙇
