### ISSUE TITLE
Degenerate Game in support_enumeration

### ISSUE THREAD

**Issue by alexalvis** [drvinceknight/Nashpy#60]
Hi, I just came across the problem, the matrix A:[[-100, 0, 0, -100],[0, 0, 0, -100],[-100, 0 ,0, 0],[0, 0, 0, -50]] do get the solution in support_enumeration(), however, the matrix B [[-100, 0, 0, -100],[0, 0, 0, -100],[-100, 0 ,0, 0],[0, 0, 0, -33.3333333]] can not get the solution and saying an even number of (0) equilibria was returned. This indicates that the game is degenerate. I checked the formal issue and thought this problem has been solved, but I don't know why this still comes to my situation. Thanks  a lot.

**Comment by drvinceknight** [comment]
Hi @alexalvis, I'm afraid I don't fully understand.

Here is what I get when I run the zero sum game with the matrix `A` you discussed:

```
>>> import nashpy as nash

>>> A = [[-100, 0, 0, -100],[0, 0, 0, -100],[-100, 0 ,0, 0],[0, 0, 0, -50]]
>>> game = nash.Game(A)
>>> list(game.support_enumeration())
[(array([0.00000000e+00, 8.43769499e-17, 3.33333333e-01, 6.66666667e-01]),
  array([0.33333333, 0.        , 0.        , 0.66666667]))]
```

If I include the second matrix `B` I get:

```
>>> B = [[-100, 0, 0, -100],[0, 0, 0, -100],[-100, 0 ,0, 0],[0, 0, 0, -33.3333333]]
>>> game = nash.Game(A, B)
>>> list(game.support_enumeration())
[(array([1., 0., 0., 0.]), array([0., 1., 0., 0.])),
 (array([1., 0., 0., 0.]), array([0., 0., 1., 0.])),
 (array([0., 1., 0., 0.]), array([1., 0., 0., 0.])),
 (array([0., 1., 0., 0.]), array([0., 1., 0., 0.])),
 (array([0., 1., 0., 0.]), array([0., 0., 1., 0.])),
 (array([0., 0., 1., 0.]), array([0., 1., 0., 0.])),
 (array([0., 0., 1., 0.]), array([0., 0., 1., 0.])),
 (array([0., 0., 1., 0.]), array([0., 0., 0., 1.])),
 (array([0., 0., 0., 1.]), array([1., 0., 0., 0.])),
 (array([0., 0., 0., 1.]), array([0., 1., 0., 0.])),
 (array([0., 0., 0., 1.]), array([0., 0., 1., 0.]))]
```

Note that this is using the latest version of Nashpy:

```
>>> nash.__version__
'0.0.18'
```

(You might need to update your Nashpy version by running `pip install -U nashpy` in your command line tool.)

I hope that helps, I'm closing this issue but feel free to reopen if you need to discuss this further.
