### ISSUE TITLE
Issue with Lemke_howson_enumeration

### ISSUE THREAD

**Issue by tlenaert** [drvinceknight/Nashpy#64]
Dear Vincent,

First of all, thank you for making this python package available. I explain the three approaches that you implemented in my course and would like to let the students play with the package.

Now the Lemke Howson implementation appears to suffer from a problem as it is unable to find one of the equilibria in the following game. I added the entire python code at the end to give all the details.  

This game has 3 equilibria, which are found by the other two approaches.
(array([1., 0., 0.]), array([1., 0.]))
(array([0.8, 0.2, 0. ]), array([0.66666667, 0.33333333]))
(array([0.        , 0.33333333, 0.66666667]), array([0.33333333, 0.66666667]))

the one in the middle is not found.

Any ideas what is happening here?
Thanks for the assistance.
Best

Tom

Type "help", "copyright", "credits" or "license" for more information.
>>> import nashpy as nash
>>> import numpy as np
>>> A=np.array([[3,3],[2,5],[0,6]])
>>> B=np.array([[3,2],[2,6],[3,1]])
>>> mygame=nash.Game(A,B)
>>> mygame
Bi matrix game with payoff matrices:

Row player:
[[3 3]
 [2 5]
 [0 6]]

Column player:
[[3 2]
 [2 6]
 [3 1]]

>>> equilibria=mygame.lemke_howson_enumeration()
>>> for eq in equilibria:
...     print(eq)
... 
(array([1., 0., 0.]), array([1., 0.]))
(array([0.        , 0.33333333, 0.66666667]), array([0.33333333, 0.66666667]))
(array([1., 0., 0.]), array([1., 0.]))
(array([1., 0., 0.]), array([1., 0.]))
(array([0.        , 0.33333333, 0.66666667]), array([0.33333333, 0.66666667]))

**Comment by drvinceknight** [comment]
Hi @tlenaert the LH algorithm is not guaranteed to find all equilibria (it guarantees finding at least one). There are some simple 2 by 2 examples for which this is relatively simple to see as the path taken along the edges of the polytope will never reach one of the equilibria.

Glad you're finding the library helpful and let me know how it goes with your students.

**Comment by tlenaert** [comment]
Thanks for the fast response Vincent.

Best

Tom
