### ISSUE TITLE
An even number of equilibria was returned, which indicates the game is degenerate

### ISSUE THREAD

**Issue by macsimilian** [drvinceknight/Nashpy#88]
Hello, I have been using Nashpy and have come across the warning that says: "An even number of equilibria was returned, which indicates the game is degenerate. Consider using another algorithm to investigate." Why is it that an even number of equilibria means the game is degenerate? Wouldn't anything other than 1 equilibria be degenerate? Also, what are the policies to follow in these cases? If there are 0 equilibria returned, then I would just set the mixed strategy to be equal across all choices. If there are multiple equilibria, then I can think of multiple options... You could choose one at random. If you do this, however, you would have to do so separately for each agent, since they can't know each other's moves. Or, you could pick the one that gives the greatest total utility, or is there some way of "averaging" all the equilibria? As far as I know, degenerate games can't be truly "solved," I am just wondering if there is any policy to follow that is valid or best. Thank you!

**Comment by drvinceknight** [comment]
Hi @macsimilian there is a known theoretical result that states that non degenerate games have an odd number of equilibria.

> Wouldn't anything other than 1 equilibria be degenerate?

No that is not the definition of a degenerate game. For example take a look at the "battle of the sexes" game, a well known 2 player 2 strategy non degenerate game with 3 equilibria.

> degenerate games can't be truly "solved,"

Equilibria can be found for degenerate games and this set of equilibria can be infinite.

Let me know if you'd like me to point you at some reading materials for these concepts.

**Comment by macsimilian** [comment]
Why is it that an even number of equilibria is degenerate and not 0 or infinity equilibria? (When nashpy outputs that 0 equilibria found, is that actually the same as infinite?) I still don't understand. And what are the best mixed strategies to follow in these cases? Thanks!

**Comment by macsimilian** [comment]
[Also asked on StackOverflow](https://stackoverflow.com/questions/62566073/policies-for-dealing-with-multiple-nash-equilibria-and-degenerate-games)
