### ISSUE TITLE
Add doctstring linter:

### ISSUE THREAD

**Issue by drvinceknight** [drvinceknight/Nashpy#91]
> A functional docstring linter which checks whether a docstring's description matches the actual function/method implementation. Darglint expects docstrings to be formatted using the Google Python Style Guide, or Sphinx Style Guide, or Numpy Style Guide.

https://github.com/terrencepreilly/darglint

**Comment by real-yfprojects** [comment]
Hi, now that darglint is a public archive, how do you replace it?
