### ISSUE TITLE
Implement asymmetric replicator dynamics

### ISSUE THREAD

**Issue by drvinceknight** [drvinceknight/Nashpy#95]
@katiemcgoldrick implemented replicator dynamics in #93 

This carries out single population replicator dynamics on a single population. 

It would be nice to add a 2 population model similar to what is described in [On evolutionarily stable strategies and replicator dynamics in asymmetric two-population games](https://www.semanticscholar.org/paper/On-evolutionarily-stable-strategies-and-replicator-Accinelli-Carrera/9bd01e105a617293e98cb6540ad3c376bd226adf).

**Comment by drvinceknight** [comment]
[Evolutionarily_Stable_Strategies_and_Replicator_Dy.pdf](https://github.com/drvinceknight/Nashpy/files/6067856/Evolutionarily_Stable_Strategies_and_Replicator_Dy.pdf)

**Comment by 11michalis11** [comment]
Successfully implemented this in #97.

**Comment by drvinceknight** [comment]
Closed by #97
